const grid = document.getElementById('area-grid');
Object.values(areas).forEach(a => grid.insertAdjacentHTML('beforeend', `<article class="area"><div class="area-icon">${a.icon}</div><h3>${a.title}</h3><p>${a.description}</p></article>`));
const testScreen = document.getElementById('test-screen'), resultScreen = document.getElementById('result-screen');
let current = 0, answers = [];
const start = () => { current=0; answers=[]; document.body.style.overflow='hidden'; testScreen.classList.remove('hidden'); renderQuestion(); };
document.getElementById('start-test').addEventListener('click', start);
document.getElementById('close-test').addEventListener('click', () => {testScreen.classList.add('hidden'); document.body.style.overflow='';});
function renderQuestion(){ const q=questions[current], answered=answers[current]!==undefined; document.getElementById('progress-label').textContent=`Вопрос ${current+1} из ${questions.length}`; document.getElementById('progress-value').style.width=`${(current/questions.length)*100}%`; document.getElementById('previous').style.visibility=current?'visible':'hidden'; document.getElementById('next').textContent=current===questions.length-1?'Показать результат →':'Далее →'; document.getElementById('next').disabled=!answered; document.getElementById('test-status').textContent=answered?'Ответ выбран. Нажмите «Далее», чтобы продолжить.':'Выберите один вариант ответа, чтобы продолжить.'; document.getElementById('question-box').innerHTML=`<p class="question-number">ВОПРОС ${String(current+1).padStart(2,'0')}</p><h2>${q[0]}</h2><p class="question-hint">Выберите вариант, который ближе всего вам.</p><div class="answers">${q[1].map((a,i)=>`<button class="answer ${answers[current]===i?'selected':''}" aria-pressed="${answers[current]===i}" data-i="${i}">${a[0]}</button>`).join('')}</div>`; document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>{answers[current]=Number(b.dataset.i);renderQuestion()})); }
document.getElementById('previous').addEventListener('click',()=>{if(current){current--;renderQuestion()}});
document.getElementById('next').addEventListener('click',()=>{if(current<questions.length-1){current++;renderQuestion()}else showResults()});
function showResults(){ const scores=Object.fromEntries(Object.keys(areas).map(k=>[k,0])); answers.forEach((answer,i)=>{const points=questions[i][1][answer][1]; Object.entries(points).forEach(([key,value])=>scores[key]+=value)}); const maximum=Math.max(...Object.values(scores)); const top=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3); testScreen.classList.add('hidden'); resultScreen.classList.remove('hidden'); const cards=top.map(([key,score],i)=>{const area=areas[key], percent=Math.round(64+(score/maximum)*29), professions=area.professions.map(profession=>`<li><a href="profession.html?id=${encodeURIComponent(profession)}">${profession} →</a></li>`).join('');return `<article class="result-card"><div class="rank">0${i+1}</div><div><h2>${area.icon} ${area.title}</h2><p>${area.result}</p><p class="profession-title">Подходящие профессии:</p><ul class="profession-list">${professions}</ul></div><div class="score">${percent}%</div></article>`}).join(''); document.getElementById('result-container').innerHTML=`<p class="result-tag">ТВОЙ ПРОФЕССИОНАЛЬНЫЙ ПРОФИЛЬ</p><h1>Вот что тебе подходит</h1><p class="result-intro">Твои ответы показали, что ты можешь особенно ярко раскрыться в этих направлениях.</p>${cards}<div class="result-actions"><button class="button button-main" id="restart">Пройти ещё раз</button><button class="button button-secondary" id="share">Скопировать ссылку</button></div><p class="interaction-status" id="share-status" role="status" aria-live="polite"></p><p class="small-note">Тест носит ознакомительный характер и не заменяет консультацию специалиста.</p>`; document.getElementById('restart').addEventListener('click',()=>{resultScreen.classList.add('hidden');start()}); document.getElementById('share').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);document.getElementById('share-status').textContent='Готово: ссылка на тест скопирована в буфер обмена.'}catch(e){document.getElementById('share-status').textContent='Не удалось скопировать ссылку. Скопируйте адрес страницы из строки браузера.'}}); }
